name: Selina's Business
favicon: null
layout_spectrum: 0.41035
typography_spectrum: 0.14023554977029562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#95c2d0'
    - '#0f0f0f'
    - '#4a5355'
    - '#7b1649'
    - '#1f86aa'
  brandStrength: 0.5186953467782587
  lightness: 0.05564304278232157
  saturation: 0.215523422928527
  rhythmicContrast: 0.7532224021852016
purpose: []
