name: Selina's Business
favicon: null
layout_spectrum: 0.7377270706929266
typography_spectrum: 0.14023554977029562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5186953467782587
  lightness: 0.05564304278232157
  saturation: 0.215523422928527
  rhythmicContrast: 0.7532224021852016
purpose: []
